FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m appuser
RUN chown -R appuser:appuser /app
USER appuser

ENV TMPDIR=/tmp

CMD ["gunicorn", "--bind=0.0.0.0:5000", "app:app"]
